classic: false

# Possible values: permission, user, group, context, size, date, name, inode, links, git
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
  - git

color:
  # Possible values: never, auto, always
  when: auto
  # Possible values: default, custom
  theme: default

no-symlink: false
total-size: false
hyperlink: never
symlink-arrow: ⇒
header: false
date: date
dereference: false
size: default
icons:
  when: auto
  theme: fancy
  separator: " "

indicators: false
layout: grid
recursion:
  enabled: false
  # depth: 3

sorting:
  # Specify what to sort by
  # Possible values: extension, name, time, size, version
  column: name
  # Whether to reverse the sorting
  # Possible values: false, true
  reverse: false
  # Whether to group directories together and where
  # When "classic" is set, this is set to "none"
  # Possible values: first, last, none
  dir-grouping: first


