[pyprland]
plugins = ["scratchpads"]

[scratchpads.browser]
command = "firefox"
class = "firefox"
lazy = true
size = "90% 90%"
animation = ""
position = "6% 6%"

[scratchpads.orgmode]
command = "neovide"
class = "neovide"
lazy = true
size = "50% 75%"
animation = ""
position = '25% 12%'
